/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    NEXT_PUBLIC_FIRE_BASE_API_KEY: process.env.FIRE_BASE_API_KEY,
    NEXT_PUBLIC_FIRE_BASE_AUTH_DOMAIN: process.env.FIRE_BASE_AUTH_DOMAIN,
    NEXT_PUBLIC_FIRE_BASE_PROJECT_ID: process.env.FIRE_BASE_PROJECT_ID,
    NEXT_PUBLIC_FIRE_BASE_STORAGE_BUCKET: process.env.FIRE_BASE_STORAGE_BUCKET,
    NEXT_PUBLIC_FIRE_BASE_MESSAGING_SENDER_ID:
      process.env.FIRE_BASE_MESSAGING_SENDER_ID,
    NEXT_PUBLIC_FIRE_BASE_APP_ID: process.env.FIRE_BASE_APP_ID,
    NEXT_PUBLIC_FIRE_BASE_MEASUREMENT_ID: process.env.FIRE_BASE_MEASUREMENT_ID,
  },
};

export default nextConfig;
